# Generated by Django 5.1.4 on 2025-01-13 05:14

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('review_stage', django_fsm.FSMField(choices=[('pending_review', 'Pending Review'), ('review_scheduled', 'Review Scheduled'), ('feedback_provided', 'Feedback Provided'), ('under_approval', 'Under Approval'), ('review_approved', 'Review Approved'), ('review_rejected', 'Review Rejected')], default='pending_review', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='system.employee')),
            ],
        ),
    ]
